/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ioc.dam.torrejon.ventanas;

import ioc.dam.torrejon.controladores.Utils;
import ioc.dam.torrejon.controladores.UsuariosController;
import java.io.IOException;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Carlos Torrejón
 */
public class CambiarContrasena extends javax.swing.JInternalFrame {

    UsuariosController user = new UsuariosController();

    JSONObject perfil = new JSONObject();

    Utils infoUser = new Utils();

    String mensaje = "Es necesario rellenar las dos casillas, quiere continuar?";

    int id, code;
    String pass, newPass;

    /**
     * Creates new form CambiarContraseña
     */
    public CambiarContrasena() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JPasswordField();
        bCambiarPass = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblId1 = new javax.swing.JLabel();
        lblMail1 = new javax.swing.JLabel();
        bPerfil = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cambiar contraseña");
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cambiar contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Antigua contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 160, -1));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 160, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nueva contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 130, -1));
        jPanel1.add(txtNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 160, -1));

        bCambiarPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bCambiarPass.setText("Cambiar contraseña");
        bCambiarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCambiarPassActionPerformed(evt);
            }
        });
        jPanel1.add(bCambiarPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 200, -1));

        lblId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 130, 30));

        lblMail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 140, 30));

        lblId1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblId1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId1.setText("Id :");
        jPanel1.add(lblId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, 30));

        lblMail1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMail1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMail1.setText("correo:");
        jPanel1.add(lblMail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 60, 30));

        bPerfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bPerfil.setText("Usuario");
        bPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(bPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCambiarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCambiarPassActionPerformed

        pass = new String(txtPass.getPassword());
        newPass = new String(txtNewPass.getPassword());

        if (pass.isEmpty() || newPass.isEmpty()) {
            Utils.OptionPane(mensaje, this);
        } else {

            try {
                id = perfil.getInt("jti");
                code = user.cambiarContrasena(pass, newPass, id);
                if(code!=200){
                    Utils.OptionPaneInfo("No se ha podido cambiar la contraseña", this);
                }
            } catch (IOException | InterruptedException ex) {
                ex.getMessage();
            } catch (NoSuchAlgorithmException |KeyManagementException |JSONException ex) {
            ex.getMessage();
        }
        }
    }//GEN-LAST:event_bCambiarPassActionPerformed

    private void bPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPerfilActionPerformed
        try {
            perfil = infoUser.DatosUsuario(Login.token);

            id = perfil.getInt("jti");
            String idUser = String.valueOf(id);
            lblMail.setText(perfil.getString("sub"));
            lblId.setText(idUser);
        } catch (JSONException ex) {
            Logger.getLogger(CambiarContrasena.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCambiarPass;
    private javax.swing.JButton bPerfil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMail1;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
